---
- name: update apt source.list
  template: src=etc/apt/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  notify: Update apt database

- meta: flush_handlers

- name: install locales
  locale_gen: name={{ item }} state=present
  with_items: ["fr_FR.UTF-8", "en_US.UTF-8"]

- name: upgrade packages
  apt: upgrade=yes force=yes

- name: upgrade kernel
  apt: name={{ item }} state=latest force=yes
  with_items: ["linux-image-generic-lts-utopic", "linux-headers-generic-lts-utopic"]
  register: upgraded_kernel

- name: reboot server
  shell: reboot
  async: 0
  poll: 0
  ignore_errors: true
  become: true
  when: upgraded_kernel.changed

- name: waiting for the reboot
  local_action: >
    wait_for
    host={{ ansible_host }}
    port={{ ansible_port }}
    state=started
    delay=30
    timeout=900
    connect_timeout=15
  when: upgraded_kernel.changed

- name: refresh ansible facts after the kernel upgrade
  action: setup
  when: upgraded_kernel.changed

- name: install common packages
  apt: name={{ item }} state=present force=yes
  with_items: [
    "linux-image-extra-{{ ansible_kernel }}",
    "linux-image-extra-virtual",
    "apt-transport-https",
    "ca-certificates",
    "ntp",
    "htop",
    "curl",
    "unzip",
    "git",
    "jq",
    "python",
    "python-pip"
  ]

- name: Restart ntp
  service: name=ntp state=restarted
