---
- name: create consul group
  group: >
    name={{ consul_group }}
    state=present
  tags: install

- name: create consul user
  user: >
    name={{ consul_user }}
    group={{ consul_group }}
    system=yes
    state=present
  tags: install

- name: create consul directories
  file: >
    state=directory
    path={{ item }}
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  with_items:
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"
    - "{{ consul_ui_dir }}"
  tags: install

- name: create consul log file
  file: >
    state=touch
    path={{ consul_log_file }}
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0644
  tags: install

- name: check consul archive stat
  stat: path={{ consul_download_folder }}/{{ consul_archive }}
  register: consul_archive_stat
  tags: install

- name: download consul
  get_url: >
    url={{ consul_download_url }}
    dest={{ consul_download_folder }}/{{ consul_archive }}
    sha256sum={{ consul_sha256 }}
  when: not consul_archive_stat.stat.exists
  register: consul_was_downloaded
  tags: install

- name: check consul bin stat
  stat: path={{ consul_bin }}
  register: consul_bin_stat
  tags: install

- name: install consul
  unarchive: >
    copy=no
    src={{ consul_download_folder }}/{{ consul_archive }}
    dest={{ consul_bin|dirname }}
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  when: consul_was_downloaded|changed or not consul_bin_stat.stat.exists
  tags: install

- name: check consul ui archive stat
  stat: path={{ consul_ui_download_folder }}/{{ consul_ui_archive }}
  register: consul_ui_archive_stat
  tags: install

- name: download consul ui
  get_url: >
    url={{ consul_ui_download_url }}
    dest={{ consul_ui_download_folder }}/{{ consul_ui_archive }}
    sha256sum={{ consul_ui_sha256 }}
  when: not consul_ui_archive_stat.stat.exists
  tags: install

- name: install consul ui
  unarchive: >
    copy=no
    src={{ consul_ui_download_folder }}/{{ consul_ui_archive }}
    dest={{ consul_ui_dir }}
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  tags: install

- name: copy consul upstart script
  template: >
    src=etc/init/consul.conf.j2
    dest=/etc/init/consul.conf
    owner=root
    group=root
    mode=0644
  tags: install

- name: ensure consul is enabled
  service: name=consul enabled=yes
  tags: install

- name: copy consul server config
  template: >
    src=etc/consul/conf.d/server.json.j2
    dest=/etc/consul/conf.d/server.json
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0644
  tags: setup

- name: ensure consul is restarted
  service: name=consul state=restarted
  tags: setup
