---
- name: ensure others dns servers are absent
  apt: name="bind9" state=absent purge=yes

- name: install dnsmasq
  apt: name={{ item }} state=present force=yes
  with_items: ["dnsmasq"]

- name: copy consul server config
  template: >
    src={{ item }}.j2
    dest=/{{ item }}
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0644
  with_items:
    - etc/dnsmasq.conf
    - etc/dnsmasq.d/10-consul

- name: ensure dnsmasq is restarted
  service: name=dnsmasq enabled=true state=restarted
